GET http://localhost:3001/tasks/?limit=3&page=1&order=asc
Content-Type: application/json 

POST http://localhost:3001/tasks/create
Content-Type: application/json 
{
    "title": "TEST",
    "description": "Description",
    "status": "todo",
    "priority": "normal",
    "dueDate": "2025-01-01T12:00:00Z"
}

PATCH http://localhost:3001/tasks/update
Content-Type: application/json 
{
    "_id":"67e43b8aef8e138bb7d4b5e8",
    "title": "change indeed"
}